karma-runner/karma-jasmine

src/adapter.js
test/adapter.spec.js

Replaces the following:
```Bash
Chrome 40.0.2214 (Mac OS X 10.9.5) xxx should return false 1 FAILED
Expected true to be false.
Error: Expected true to be false.
at stack (/foo/bar/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1441:17)
at buildExpectationResult (/foo/bar/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1411:14)
at Spec.Env.expectationResultFactory (/foo/bar/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:533:18)
at Spec.addExpectationResult (/foo/bar/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:293:34)
at Expectation.addExpectationResult (/foo/bar/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:477:21)
at Expectation.toBe (/foo/bar/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1365:12)
at /foo/bar/baz.spec.js:23:29
at …
```

fix(adapter): cleanup error stack trace

---

README.md
src/adapter.js
src/adapter.wrapper
test/adapter.spec.js

Related issue in `karma` https://github.com/karma-runner/karma/issues/1235

feat: add grep option like in karma-mocha

---

src/adapter.js

This addresses issue #80 — [TypeError: relevantStack[0] is undefined](https://github.com/karma-runner/karma-jasmine/issues/80).

fix(adapter): check if `relevantStack` array is empty

---

src/adapter.js
test/adapter.spec.js

The displayed error message is incorrectly formatted when the message contains new-line characters, since getRelevantStackFrom() splits the stack on new-line characters.
This pull request addresses issue #79

fix(adapter): remove error message from stack prior to processing stack

---

src/adapter.js
test/adapter.spec.js

Use case:
If an error is thrown from within karma or jasmine during the running of a test, and this stack trace only contains karma- or jasmine-related entries, then debugging the error can be difficult because an empty stack trace will be logged to the console.
This PR changes the stack entry filtering such that entries from within karma or jasmine will be considered 'relevant' if these are the only frames in the stack, thereby preventing a scenario where an empty stack trace will be served up.

feat(adapter): do not filter out karma/jasmine frames from stack if the stack consists entirely of said frames

---

.travis.yml
package.json
src/adapter.js
test/adapter.spec.js

I had to make additional changes to this to make it work:
1. Had to update the test suite to work with newer jasmine, karma, etc. in order to install it locally or in TravisCI for testing purposes
2. Updated the adapter test to use jasmine 2 syntax (`.and.returnValue` instead of `.andReturn`, for example)
3. Had to specify Firefox as an addon in the .travis.yml file to get Firefox loaded
4. Had to change the node version in .travis.yml (switched to 0.12; I don't know if you want it to be a newer version or if you want to keep using the 0.x branch)
The changes I made:
1. If it's an array, process it as such instead of joining it into a string. This allows us to more cleanly match the --grep option and return its value
2. If it's a string, use the solution I documented in issue #102 …

Fix #102 - --grep option only works if it's the first argument

---

.gitignore
integration-tests.sh

Now ./integration-test.sh runs all integration tests because pass incorrect parameters to ./run.sh and also this tests does not run on builded.zip.
Current commit fix this. But we **also should fix** `./run.sh` because there we set `set -e`
and exit on line `  MATCH_COUNT=$(echo $DIR | egrep -c -e "$GREP")` because if egrep does not match line it exits with status code 1

chore: fix integration test

---

src/adapter.js
test/adapter.spec.js

feat: report status of the spec closes #129

---

src/adapter.js
test/adapter.spec.js

If an error is thrown in an afterAll block, it needs to be handled
specially since the error isn't attached to a specific spec.  This
change won't fail any specific test, but will cause a general failure
which will still cause overall run failure.
Closes #161

feat: Propagate errors thrown in afterAll blocks

---

.travis.yml
package.json

In this patch The version is bumped to 2.0.0, because it removes the support for node < 4.
Added tests for node version 6 and 8 as well

Update the version to 2.0.0 and restrict node version available to 4.0

---

src/adapter.js
test/adapter.spec.js

Time reporting broke since jasmine-core v2.9 because the reporter API
now receives copies of spec results instead of the real deal.
We cannot rely on the same object being passed around.
Fixes #196

fix(time): report correct time since Jasmine v2.9.0

---

README.md
package.json
src/adapter.js
test/adapter.spec.js

Jasmine 3.0 uses a status of `excluded` instead of `disabled` and has a new option to `failFast`.
Since Jasmine 3.0 also defaults to running specs in random order, I also had to update a few of the existing specs to use `spyOn` so the spies get cleaned up and don't pollute other specs.

Add support for Jasmine 3.0

---

src/adapter.js
test/adapter.spec.js

The string tested in the function isTopLevelSuite() is not used in jasmine. The
correct string would be Jasmine__TopLevel__Suite (two underscores). So the function
always returns false, and we negate it at the call site, to the child is always
added. That's the correct behavior because we already have a root node matching
the Jasmine top level suite. The test and the function is unnecessary.

Remove incorrect function and its call.

---

src/adapter.js
test/adapter.spec.js

This commit appends the field 'fullName' to the result sent back to the
Karma server. The full name is useful to identify the exact spec that
was run.
API for specResult: https://jasmine.github.io/api/2.9/global.html#SpecResult

adapter.js: Include full name of spec in specDone()

---

src/adapter.js
test/adapter.spec.js

To use real regular expressions, use the traditional JavaScript syntax:
> karma run -- --grep=/&lt;regex&gt;/&lt;flags&gt;
Sample:
> karma run -- --grep=/.&#42;should.&#42;/i
This implementation only extends the functionality without breaking the existing syntax.
You can continue to use the old syntax:
> karma run -- --grep=RootTestSuite

--grep option now supports real regular expressions but not masks only.

---

test/adapter.spec.js

I fix return value for matching spec (`should return the all stack entries if every entry is irrelevant`).

fix: return false for every entry is irrelevant

---

README.md
package-lock.json
package.json
src/adapter.js
test/adapter.spec.js

Manually tested, and confirmed to work with Jasmine@3.0.0 and Jasmine@3.3.0.
Resolves #221
Needs:
- A way to automate testing in the different versions of Jasmine

Handle Jasmine 3.3

---

src/adapter.js
test/adapter.spec.js

Chrome devtools looks for a pattern in stack traces and if it finds a match
it will shorten and linkify the stack, and apply sourcemaps. The pattern fails
when the "Error: " is removed. So we put it back for debugging's sake.

fix(console): Re-add Error: to the stack

---

src/adapter.js

Should fix [issue#218](https://github.com/karma-runner/karma-jasmine/issues/218). Sadly I'm having a hard time understanding the project, so the fix is as minimal as possible and no refactoring was done.
The commit merely moves up the configuration in `createStartFn()`, so that it happens as soon as `createStartFn()` is called. Before this commit, the configuration was only performed, once `window.__karma__.start()` was called.

Configuration in createStartFn now happens outside the returned startFn

---

src/adapter.js
test/adapter.spec.js

In the next version of Jasmine, a new configuration option `failSpecWithNoExpectations` will be added. If turned ON, Jasmine will be reporting specs that have not run any expectations as `failed` Subsequently, this change is to update the adapter for such scenario.
See [the corresponding feature request in Jasmine](https://github.com/jasmine/jasmine/issues/1740). Please don't mind the Closed status of the Issue/PR, and see [from the pull request comments and history](https://github.com/jasmine/jasmine/pull/1743) that the feature has already been implemented/merged into Jasmine. The status is Closed because the owner merged and closed it manually.

feat(adapter): handle new Jasmine optional behavior for specs without expectations

---

src/adapter.js
test/adapter.spec.js

Avoids duplicates with a clearer algorithm

refactor(adapter): Simplify message+stack processing.

---

src/adapter.js

Since the user might mock Dates in tests, KarmaReporter saves a reference to the native Date and uses that reference for measuring duration. The problem is that it only works when users follows best practises when writing tests. 
If a user writes a "bad" test where the Date is mocked in the body of a `decribe` instead of inside an `it` or `beforeEach`, the Date is already mocked by the time KarmaReporter is called.
By saving the reference at the time adapter.js is executed instead of when KarmaReporter is called, this problem is prevented.
**Nothing prevents a developer from writing:**
```javascript
describe('foo', function () {
jasmine.clock().mockDate(new Date(0));
it('bar', function () {
});
}
```
Before the change in this PR, a test like the one above would cause the duration of the …

Fixed so that timing will always use native Date for rare cases

---

.travis.yml

* remove the obsolete `sudo: false`
* remove the `dist` property; xenial is the default
* remove the obsolete npm update step
* stop installing grunt-cli since it's already available
* add the explicit `cache: npm`
* combine the test scripts so that if the first fails the whole build will fail

chore: Tweak Travis CI config

---

README.md
src/adapter.js
src/adapter.wrapper
test/adapter.spec.js

Refactor spec selection to make multiple alternative selection mechanisms
easier to implement.
Print a debug URL on failures and focus on that single test if the URL
is pasted.
Add low-level sharding support.

feat(adapter): Support spec=name URL and sharding.

---

src/adapter.js

Surprise: someone uses karma-jasmine with native=script.
Fixes #262

fix(adapter): do not emit debug url unless in a browser

---

src/adapter.js
test/adapter.spec.js

jasmine tests are named suite-name + spec-name. The links printed by
karma-jasmine-html-reporter include links for suite-name (only). To support
running the suite, allow the filter to match any part of the test name.
Fixes #256

fix(filter): match any portion of a spec name

---

src/adapter.js

We received a bug report in `karma-electron`, https://github.com/twolfson/karma-electron/issues/47, which eventually traced back to Electron being unable to pass a `function` to between Karma contexts due to IPC fixing passing references between processes
This PR resolve that bug by removing the `function` which was being attempted to pass as a reference between processes
In this PR:
- Remove `Order.sort` function passing to Karma callback
- Fixes https://github.com/twolfson/karma-electron/issues/47
Feel free to request commit message changes (or apply them yourself). I tried to find documentation on them but was running out of time =/

Remove `Order.sort` function passing to Karma callback

---

src/adapter.js

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

refactor: replace deprecated String.prototype.substr()

---

.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml
package-lock.json
package.json

Fixes https://github.com/karma-runner/karma-jasmine/issues/311

ci: lint and commitlint in its own workflow

---

.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml
.gitignore
package-lock.json
package.json

~~Requires #296 so that we have CI running.~~
Fixes #303, fixes #304 along the way
TODO:

Update dependencies and drop Node.js 10 support

---

README.md

It is not self-explanatory that grep will recognize whether the input string is a regex or not. In the case of a string it sanitizes it to turn it into a regex.

Make grep behavior clearer in README

---

src/adapter.js

improve this.matches function performance by converting indexof loop to Set (hashtable) has. O(n) to O(1) fixes: https://github.com/karma-runner/karma-jasmine/issues/302

fix: fixes matches performance issue, github#302

---

README.md
src/adapter.js
test/adapter.spec.js
test/fixtures/custom-filter/karma.conf.js
test/fixtures/custom-filter/test/custom-filter.spec.js

Allow users to define their own jasmine `specFilter`.
```js
jasmine.getEnv().configure({
specFilter: function(spec) {
// ...
}
})
```
Fixes #273

feat(spec-filter): allow custom specFilter
